version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    groups:
      commitlint:
        patterns:
          - '@commitlint*'
      storybook:
        patterns:
          - '@storybook*'
          - 'storybook*'
      typescript-eslint:
        patterns:
          - '@typescript-eslint*'
      playwright:
        patterns:
          - '@playwright/test'
          - '@sand4rt/experimental-ct-web'
