name: main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  install:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
  check-format:
    name: Check Format
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - run: yarn format:check
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - run: yarn lint --format junit -o reports/lint-results.xml
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: lint-results
          path: reports/lint-results.xml
  check-types:
    name: Check Typescript Types
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - run: yarn check-types
  unit-test:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - run: yarn test:coverage --ci --reporters=default --reporters=jest-junit
        env:
          JEST_JUNIT_OUTPUT_FILE: 'reports/unit-test-results.xml'
      - run: yarn codecov
        if: always()
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: unit-test-results
          path: reports/unit-test-results.xml
  e2e-test:
    name: E2E Tests
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - run: yarn test:e2e --ci --reporters=default --reporters=jest-junit
        env:
          JEST_JUNIT_OUTPUT_FILE: 'reports/e2e-test-results.xml'
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: e2e-test-results
          path: reports/e2e-test-results.xml
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [check-format, lint, check-types, unit-test, e2e-test]
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - run: yarn build
      - uses: actions/upload-artifact@v2
        with:
          name: bundle
          path: hello-web-components.min.*
  size:
    name: Check Size
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - uses: actions/download-artifact@v2
        with:
          name: bundle
      - run: yarn size
