name: reports
on:
  workflow_run:
    workflows: ['main']
    types:
      - completed
jobs:
  report-unit-test:
    name: Unit Tests Report
    runs-on: ubuntu-latest
    needs: [unit-test]
    steps:
      - uses: dorny/test-reporter@v1
        with:
          artifact: unit-test-results
          name: Unit Tests Report
          path: reports/unit-test-results.xml
          reporter: jest-junit
